### PR TITLE
docs: Simplify usage

### PR DESCRIPTION
**Pull request by l0b0**
## Reference

[Code review checklist](CODING.md#Code-review-checklist)

### CODE REVIEW

**Review by MitchellPaff — APPROVED** [review]

**Review by billgeo — COMMENTED** [review]
As far as the USAGE.md changes go, it LGTM. Will leave to other to approve the code changes.

**Review by imincik — COMMENTED** [review]
I like this change.

The only small problem is env prefix in function name (for example `prod-datasets`). It might be confusing if Data Lake is deployed to environment with different name. So maybe better to set and use `ENV` variable here.

**Comment by l0b0** [comment]
> The only small problem is env prefix in function name (for example `prod-datasets`). It might be confusing if Data Lake is deployed to environment with different name. So maybe better to set and use `ENV` variable here.

But we're going to deploy to a single prefix (or no prefix) in any case, right? And that production instance is probably going to run for years under the same name. What is the use case for end users using any of the other environments?

**Comment by imincik** [comment]
This is public repo and users can deploy under any prefix and we have other test envs as well

**Review by imincik — DISMISSED** [review]

**Review by imincik — APPROVED** [review]

**Pull request merged**
