### PR TITLE
feat: Tweak variables

### PR DESCRIPTION
**Pull request by l0b0**

### CODE REVIEW

**Review by imincik — CHANGES_REQUESTED** [review]
@l0b0 , looks like changes in `backend/tests/test_datasets_endpoint.py` could go as separate PR.

**Comment by imincik** [comment]
Or we shouldn't squash PR before merge if we want to merge PR as it is now.

**Comment by imincik** [comment]
@l0b0 , I still see those changes in `backend/tests/test_datasets_endpoint.py`

**Comment by l0b0** [comment]
> @l0b0 , I still see those changes in `backend/tests/test_datasets_endpoint.py`

Ah, you meant all of them? I've left all the `backend/tests/test_datasets_endpoint.py` changes in this PR and created [another PR](https://github.com/linz/geospatial-data-lake/pull/100) for the rest.

**Review by imincik — APPROVED** [review]
Thanks @l0b0

**Pull request merged**
